# FOX_RECOVERY_VENDOR_BOOT_PARTITION="/dev/block/by-name/vendor_boot"
OF_USE_LZ4_COMPRESSION := 1
OF_USE_AIDL_BOOT_CONTROL := 1
OF_SKIP_POST_DECRYPT_THEME_RELOAD := 1
OF_USE_DMCTL := 1
OF_MAINTAINER := Marc-Rm14
OF_USE_AIDL_BOOT_CONTROL := 1
